[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=61", "wheel"]

[project]
name = "invenio-remote-api-provisioner"
version = "0.1.0.dev1"
description = "A generic framework for provisioning external APIs for InvenioRDM events relating to records and communities"
readme = "README.md"
keywords = ["groups", "invenio", "inveniordm", "research", "social"]
license = { file = "LICENSE" }
authors = [{ name = "MESH Research", email = "scottia4@msu.edu" }]
requires-python = ">=3.9"

classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Web Environment",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
  "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
  "click",
  "invenio-app-rdm[opensearch2]<14",
  "opensearch-dsl",
  "psycopg2-binary",
  "python-iso639",
]
optional-dependencies.dev = [
  "bumpver",
  "check-manifest",
  "docker-services-cli",
  "pip-tools",
  "pytest>=7.3.2",
  "pytest-invenio",
  "pytest-runner",
  "requests-mock",
]
urls.Homepage = "https://github.com/MESH-Research/invenio-remote-api-provisioner"
entry-points."invenio_base.api_apps".invenio_remote_api_provisioner = "invenio_remote_api_provisioner.ext:InvenioRemoteAPIProvisioner"
entry-points."invenio_base.apps".invenio_remote_api_provisioner = "invenio_remote_api_provisioner.ext:InvenioRemoteAPIProvisioner"
entry-points."invenio_celery.tasks".invenio_remote_api_provisioner = "invenio_remote_api_provisioner.tasks"
entry-points."invenio_queues.queues".invenio_remote_api_provisioner = "invenio_remote_api_provisioner.queues:declare_queues"

[tool.check-manifest]
ignore = [
  "PKG-INFO",
  ".egg-info",
  ".egg-info/*",
  "setup.cfg",
  ".DS_Store",
  ".hgtags",
  ".hgsigs",
  ".hgignore",
  ".gitignore",
  ".bzrignore",
  ".gitattributes",
  ".github/*",
  ".travis.yml",
  "Jenkinsfile",
  "* .mo",
  "dist/*",
  "build/*",
  "invenio_record_importer_kcworks/dependencies/*",
]

[tool.pytest.ini_options]
addopts = "--doctest-glob='*.rst' --doctest-modules --ignore=tests/helpers"
testpaths = ["tests", "invenio_remote_api_provisioner"]

[tool.bumpver]
current_version = "0.1.0.dev1"
version_pattern = "MAJOR.MINOR.PATCH[-TAGNUM]"
commit_message = "bump version {old_version} -> {new_version}"
tag_message = "{new_version}"
tag_scope = "default"
pre_commit_hook = ""
post_commit_hook = ""
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = ['version = "{version}"', 'current_version = "{version}"']
"README.md" = ["Version {version}"]
"VERSION" = ['^"{version}"']
"invenio_record_importer_kcworks/__init__.py" = ['^__version__ = "{version}"']
